### ISSUE TITLE
Endpoints API [MD file]

### ISSUE THREAD

**Issue by ldmfabio** [fabricadesoftware-ifc/fabricaNews_backEnd#17]
Migration from google drive to markdown file

**Comment by augustebalsanel** [comment]
@ldmfabio could it be created a issue for the `Non-functional` and `Functional Requirements` to start committing the development of those files? or maybe change this specific issue to be about not only `Endpoints`, but the ones I commented before.

**Comment by ViniciusAcordiSoethe** [comment]
I dont know if its allowed, but i went to close the issue, to speed up the process and start the refactoring
