### ISSUE TITLE
(back)[update]: Fazer arquivo .env 

### ISSUE THREAD

**Issue by suethttps** [fabricadesoftware-ifc/fabricaNews_backEnd#58]
Baseando-se no passo 24 do tutorial Django do Professor Marco Andre [django-drf-tutorial](https://github.com/marrcandre/django-drf-tutorial) 

Criar o um arquivo para conter as informações importantes da aplicação ainda mais visto que ela é open code 

Para isso você vai precisar do pacote `django_environ`:

Instale usando o comando:

```shell
pdm add django-environ
```

Então edite o arquivo `config/settings.py`
Protegendo as informações importantes

segue um EXEMPLO 

```python
...
import environ
...
# Carrega as variáveis de ambiente do sistema operacional e as prepara para usá-las
env = environ.Env()
environ.Env.read_env((os.path.join(BASE_DIR, '.env')))

SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env('ALLOWED_HOSTS').split(',')
DATABASES = {'default': env.db()}
```

Crie o arquivo `.env` e adicione nele as informações que estavam em `config/settings.py`

segue um EXEMPLO

```python
SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBUG=True
ALLOWED_HOSTS=localhost,127.0.0.1
DATABASE_URL=sqlite:///db.sqlite3
```

**Comment by davigtomaz** [comment]
Feito o arquivo do .env seguindo os passos do tutorial acima.

**Comment by suethttps** [comment]
Davi fui fazer a instalação do servido em casa e percebi que foi esquecido de criar um arquivo de exemplo ou uma .env-template para servi como base na instalação de novos ambientes por favor corrija
