### ISSUE TITLE
(back)[Fix]: Reorganizar user

### ISSUE THREAD

**Issue by suethttps** [fabricadesoftware-ifc/fabricaNews_backEnd#59]
As models que tem relação critica com user devem ser refatoradas para fora da pasta `core` criando um app separado
visto que a autenticação será feita por outro serviço. 

```shell
pdm run python manage.py startapp NomeDoApp
```

**Comment by LucasLutf** [comment]
Estou com duvidas nas **models que tem relação critica com user**, criei o app user e adicionei a model user, gostaria de saber quais models são realmente **criticas** com user, já que ao meu ver quase todas models dependem de user.

**Comment by suethttps** [comment]
Duvida respondida Presencial porem são as classes ( User , UserInteractions , UserProjectFollow)

**Comment by suethttps** [comment]
Bom, dada a dificuldade enfrentada eu vou assumir essa branch tbm

**Comment by suethttps** [comment]
Sendo assim pode subir a branch 59 que eu vou tentar fazer algo nela tbm
